version: "3.9"
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # networks:
    #   - web_app

  client:
    build: .
    container_name: client
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    # networks:
    #   - web_app
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - client
#     networks:
#       - web_app
# networks:
#   web_app:
#     driver: bridge