name: CD

on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    uses: itallogravina/Trabalho-Individual-2021-2/.github/workflows/ci.yml@main

  deploy:
    needs: continuous-integration

    name: cd
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:aplicacao"
          # file: "/aplicacao/Dockerfile"
          push: true
          tags: itallogravina/gces-deploy:latest 